// Lavozim va bo'lim nomlarini turli tillarga tarjima qilish
// akela-staffing.json dagi ma'lumotlar original rus tilida

import type { Locale } from "./akela-content";

const ROLE_UZ: Record<string, string> = {
  "Генеральный директор (CEO)": "Bosh direktor (CEO)",
  "Исполнительный директор (CEOО)": "Ijrochi direktor (COO)",
  "Управляющий директор (СМО)": "Boshqaruvchi direktor (CMO)",
  "HR-менеджер": "HR-menejer",
  "Директор по маркетингу и продажам (CSO)": "Marketing va savdo bo'yicha direktor (CSO)",
  "Финансовый директор (CFO)": "Moliyaviy direktor (CFO)",
  "Операционный директор (COO)": "Operatsion direktor (COO)",
  "Менеджер по продажам": "Savdo menejeri",
  "Менеджер по продажам проектных услуг": "Loyiha xizmatlari savdo menejeri",
  "Менеджер по продажам продуктных услуг": "Mahsulot xizmatlari savdo menejeri",
  "Менеджер по продажам запчастей": "Ehtiyot qismlar savdo menejeri",
  "Менеджер по продажам логистических услуг": "Logistika xizmatlari savdo menejeri",
  "Маркетолог": "Marketolog",
  "Главный бухгалтер": "Bosh hisobchi",
  "Бухгалтер": "Buxgalter",
  "Старший бухгалтер": "Katta buxgalter",
  "Менеджер по закупкам": "Xarid menejeri",
  "Специалист по закупкам": "Xarid mutaxassisi",
  "Менеджер по логистике": "Logistika menejeri",
  "Специалист по логистике": "Logistika mutaxassisi",
  "Кладовщик": "Omborchi",
  "Инженер технической поддержки": "Texnik qo'llab-quvvatlash muhandisi",
  "Менеджер по технической поддержке": "Texnik qo'llab-quvvatlash menejeri",
  "Супервайзер": "Nazoratchi",
  "Руководитель отдела": "Bo'lim rahbari",
  "Специалист отдела": "Bo'lim mutaxassisi",
  "Менеджер": "Menejer",
  "HR-менеджер/коуч-менеджер": "HR-menejer / Kouch-menejer",
  "Системный администратор": "Tizim administratori",
  "Офис-менеджер": "Ofis-menejer",
  "Менеджер колл-центра": "Call-markaz menejeri",
  "Оператор колл-центра": "Call-markaz operatori",
  "Супервайзер колл-центра": "Call-markaz nazoratchisi",
  "Главный инженер": "Bosh muhandis",
  "Менеджер по персоналу": "Kadrlar menejeri",
  "Аудитор": "Auditor",
  "Координатор": "Koordinator",
  "Менеджер проекта": "Loyiha menejeri",
  "Директор": "Direktor",
  "Продавец": "Sotuvchi",
  "Сотрудник": "Xodim",
};

const ROLE_EN: Record<string, string> = {
  "Генеральный директор (CEO)": "General Director (CEO)",
  "Исполнительный директор (CEOО)": "Executive Director (COO)",
  "Управляющий директор (СМО)": "Managing Director (CMO)",
  "HR-менеджер": "HR Manager",
  "Директор по маркетингу и продажам (CSO)": "Director of Marketing & Sales (CSO)",
  "Финансовый директор (CFO)": "Finance Director (CFO)",
  "Операционный директор (COO)": "Operations Director (COO)",
  "Менеджер по продажам": "Sales Manager",
  "Менеджер по продажам проектных услуг": "Project Services Sales Manager",
  "Менеджер по продажам продуктных услуг": "Product Services Sales Manager",
  "Менеджер по продажам запчастей": "Spare Parts Sales Manager",
  "Менеджер по продажам логистических услуг": "Logistics Services Sales Manager",
  "Маркетолог": "Marketer",
  "Главный бухгалтер": "Chief Accountant",
  "Бухгалтер": "Accountant",
  "Старший бухгалтер": "Senior Accountant",
  "Менеджер по закупкам": "Procurement Manager",
  "Специалист по закупкам": "Procurement Specialist",
  "Менеджер по логистике": "Logistics Manager",
  "Специалист по логистике": "Logistics Specialist",
  "Кладовщик": "Warehouse Keeper",
  "Инженер технической поддержки": "Technical Support Engineer",
  "Менеджер по технической поддержке": "Technical Support Manager",
  "Супервайзер": "Supervisor",
  "Руководитель отдела": "Department Head",
  "Специалист отдела": "Department Specialist",
  "Менеджер": "Manager",
  "HR-менеджер/коуч-менеджер": "HR Manager / Coach Manager",
  "Системный администратор": "System Administrator",
  "Офис-менеджер": "Office Manager",
  "Менеджер колл-центра": "Call Center Manager",
  "Оператор колл-центра": "Call Center Operator",
  "Супервайзер колл-центра": "Call Center Supervisor",
  "Главный инженер": "Chief Engineer",
  "Менеджер по персоналу": "Personnel Manager",
  "Аудитор": "Auditor",
  "Координатор": "Coordinator",
  "Менеджер проекта": "Project Manager",
  "Директор": "Director",
  "Продавец": "Salesperson",
  "Сотрудник": "Employee",
};

const DEPT_UZ: Record<string, string> = {
  "AKELA GROUP": "AKELA GROUP (Bosh ofis)",
  "Департамент управления AGM/101": "Boshqaruv departamenti AGM/101",
  "Отдел управления AGM/101/01": "Boshqaruv bo'limi AGM/101/01",
  "Отдел офиса AGM/101/02": "Ofis bo'limi AGM/101/02",
  "Отдел корпоративной безопасности AGM/101/03": "Korporativ xavfsizlik bo'limi AGM/101/03",
  "Административно-хозяйственный отдел (АХО) AGM/101/04": "Ma'muriy-xo'jalik bo'limi (AXO) AGM/101/04",
  "Колл-центр AGM/101/05": "Call-markaz AGM/101/05",
  "Департамент по работе с персоналом AGM/102": "Kadrlar bilan ishlash departamenti AGM/102",
  "Департамент Маркетинга и продаж AGM/103": "Marketing va savdo departamenti AGM/103",
  "Отдел проектных продаж AGM/103/01": "Loyiha savdo bo'limi AGM/103/01",
  "Отдел продуктных продаж AGM/103/02": "Mahsulot savdo bo'limi AGM/103/02",
  "Отдел продаж запасных частей AGM/103/03": "Ehtiyot qismlar savdo bo'limi AGM/103/03",
  "Отдел продаж услуг логистики и контрактации AGM/103/04": "Logistika va shartnoma xizmatlari savdo bo'limi AGM/103/04",
  "Отдел Маркетинга AGM/103/08": "Marketing bo'limi AGM/103/08",
  "Финансовый департамент AGM/104": "Moliyaviy departament AGM/104",
  "Отдел бухгалтерии и финансового учёта AGM/104/03": "Buxgalteriya va moliyaviy hisob bo'limi AGM/104/03",
  "Операционный департамент AGM/105": "Operatsion departament AGM/105",
  "Отдел закупа AGM/105/01": "Xarid bo'limi AGM/105/01",
  "Отдел логистики и контрактации AGM/105/02": "Logistika va shartnoma bo'limi AGM/105/02",
  "Отдел склада AGM/105/03": "Ombor bo'limi AGM/105/03",
  "Oтдел технической поддержки AGM/105/04": "Texnik qo'llab-quvvatlash bo'limi AGM/105/04",
};

const DEPT_EN: Record<string, string> = {
  "AKELA GROUP": "AKELA GROUP (Head Office)",
  "Департамент управления AGM/101": "Management Department AGM/101",
  "Отдел управления AGM/101/01": "Management Division AGM/101/01",
  "Отдел офиса AGM/101/02": "Office Division AGM/101/02",
  "Отдел корпоративной безопасности AGM/101/03": "Corporate Security Division AGM/101/03",
  "Административно-хозяйственный отдел (АХО) AGM/101/04": "Administrative & Economic Division (AEC) AGM/101/04",
  "Колл-центр AGM/101/05": "Call Center AGM/101/05",
  "Департамент по работе с персоналом AGM/102": "Human Resources Department AGM/102",
  "Департамент Маркетинга и продаж AGM/103": "Marketing & Sales Department AGM/103",
  "Отдел проектных продаж AGM/103/01": "Project Sales Division AGM/103/01",
  "Отдел продуктных продаж AGM/103/02": "Product Sales Division AGM/103/02",
  "Отдел продаж запасных частей AGM/103/03": "Spare Parts Sales Division AGM/103/03",
  "Отдел продаж услуг логистики и контрактации AGM/103/04": "Logistics & Contracting Sales Division AGM/103/04",
  "Отдел Маркетинга AGM/103/08": "Marketing Division AGM/103/08",
  "Финансовый департамент AGM/104": "Finance Department AGM/104",
  "Отдел бухгалтерии и финансового учёта AGM/104/03": "Accounting & Financial Reporting Division AGM/104/03",
  "Операционный департамент AGM/105": "Operations Department AGM/105",
  "Отдел закупа AGM/105/01": "Procurement Division AGM/105/01",
  "Отдел логистики и контрактации AGM/105/02": "Logistics & Contracting Division AGM/105/02",
  "Отдел склада AGM/105/03": "Warehouse Division AGM/105/03",
  "Oтдел технической поддержки AGM/105/04": "Technical Support Division AGM/105/04",
};

const NAME_MAP: Record<string, string> = {
  "Кадиров Акбар Абдуманнапович": "Kadirov Akbar Abdumanapovich",
  "Реджепова Гулнара": "Redjepova Gulnara",
  "Атаева Айнур": "Ataeva Aynur",
  "Реджепов Батыр": "Redjepov Batyr",
  "Юлдашева Мавлюда": "Yuldasheva Mavlyuda",
  "Юлдашева Дилфуза": "Yuldasheva Dilfuza",
  "Сафаров Улугбек": "Safarov Ulugbek",
  "Рустамов Жасур": "Rustamov Jasur",
  "Кенжаев Шухрат": "Kenjaev Shuhrat",
  "Юлдашев Алишер": "Yuldashev Alisher",
  "Кенжаев Достон": "Kenjaev Doston",
  "Тураев Шавкат": "Turaev Shavkat",
  "Хаитов Алишер": "Haitov Alisher",
  "Юлдашев Жасур": "Yuldashev Jasur",
  "Абдуллаев Акмал": "Abdullaev Akmal",
  "Сафаров Бахтиёр": "Safarov Bakhtiyor",
  "Эргашев Бахтиёр": "Ergashev Bakhtiyor",
  "Юлдашев Бахтиёр": "Yuldashev Bakhtiyor",
  "Юлдашев Ойбек": "Yuldashev Oybek",
  "Хакимов Шавкат": "Hakimov Shavkat",
  "Кучкаров Алишер": "Kuchkarov Alisher",
  "Кучкарова Мадина": "Kuchkarova Madina",
  "Тошев Бахтиёр": "Toshev Bakhtiyor",
  "Эргашев Улугбек": "Ergashev Ulugbek",
  "Алимов Жасур": "Alimov Jasur",
  "Алимов Акмал": "Alimov Akmal",
  "Юлдашев Достон": "Yuldashev Doston",
  "Эргашева Дилфуза": "Ergasheva Dilfuza",
  "Юлдашева Дилноза": "Yuldasheva Dilnoza",
  "Эргашев Достон": "Ergashev Doston",
  "Тошев Достон": "Toshev Doston",
  "Юлдашева Нигора": "Yuldasheva Nigora",
  "Юлдашева Нилуфар": "Yuldasheva Nilufar",
  "Эргашев Жасур": "Ergashev Jasur",
  "Юлдашев Дилмурод": "Yuldashev Dilmurod",
  "Кучкаров Бахтиёр": "Kuchkarov Bakhtiyor",
  "Юлдашев Отабек": "Yuldashev Otabek",
  "Юлдашев Акмал": "Yuldashev Akmal",
  "Юлдашев Улугбек": "Yuldashev Ulugbek",
  "Юлдашев Шавкат": "Yuldashev Shavkat",
  "Юлдашев Фаррух": "Yuldashev Farrukh",
  "Кенжаев Бахтиёр": "Kenjaev Bakhtiyor",
  "Кучкарова Дилфуза": "Kuchkarova Dilfuza",
  "Кенжаев Улугбек": "Kenjaev Ulugbek",
  "Юлдашева Мадина": "Yuldasheva Madina",
  "Тошев Улугбек": "Toshev Ulugbek",
  "Алимов Бахтиёр": "Alimov Bakhtiyor",
  "Эргашева Мадина": "Ergasheva Madina",
  "Тошев Алишер": "Toshev Alisher",
  "Алимов Улугбек": "Alimov Ulugbek",
  "Алимов Достон": "Alimov Doston",
  "Эргашев Акмал": "Ergashev Akmal",
  "Алимов Шавкат": "Alimov Shavkat",
};

export function translateRole(role: string, locale: Locale = "uz"): string {
  if (locale === "ru") return role;
  const map = locale === "en" ? ROLE_EN : ROLE_UZ;
  return map[role] || role;
}

export function translateDepartment(dept: string, locale: Locale = "uz"): string {
  if (locale === "ru") return dept;
  const map = locale === "en" ? DEPT_EN : DEPT_UZ;
  return map[dept] || dept;
}

export function translateName(name: string): string {
  return NAME_MAP[name] || name;
}
